/* Auto-generated by analysis/generate_oscillator_tables.py. */
#ifndef OSCILLATOR_TABLES_H
#define OSCILLATOR_TABLES_H

#include <stdint.h>

#define OSCILLATOR_TABLE_SIZE 1024U
#define OSCILLATOR_MIP_LEVEL_COUNT 9U

extern const uint16_t oscillator_mip_max_harmonic[OSCILLATOR_MIP_LEVEL_COUNT];
extern const int16_t oscillator_saw_mip_tables[OSCILLATOR_MIP_LEVEL_COUNT][OSCILLATOR_TABLE_SIZE];
extern const int16_t oscillator_square_mip_tables[OSCILLATOR_MIP_LEVEL_COUNT][OSCILLATOR_TABLE_SIZE];

#endif /* OSCILLATOR_TABLES_H */
