"""Generate band-limited int16 wavetable banks for the STM32 firmware."""

from pathlib import Path

import numpy as np


TABLE_SIZE = 1024
MAX_HARMONICS = (511, 255, 127, 63, 31, 15, 7, 3, 1)
OUTPUT_DIRECTORY = (
    Path(__file__).resolve().parents[1]
    / "ST"
    / "STM32F3_Embedded_Synth"
    / "Core"
    / "Inc"
)
HEADER_PATH = OUTPUT_DIRECTORY / "oscillator_tables.h"
SOURCE_PATH = OUTPUT_DIRECTORY.parent / "Src" / "oscillator_tables.c"


def generate_saw(max_harmonic: int) -> np.ndarray:
    phase = np.arange(TABLE_SIZE, dtype=np.float64) / TABLE_SIZE
    signal = np.zeros(TABLE_SIZE, dtype=np.float64)
    for harmonic in range(1, max_harmonic + 1):
        signal -= np.sin(2.0 * np.pi * harmonic * phase) / harmonic
    return normalize(signal)


def generate_square(max_harmonic: int) -> np.ndarray:
    phase = np.arange(TABLE_SIZE, dtype=np.float64) / TABLE_SIZE
    signal = np.zeros(TABLE_SIZE, dtype=np.float64)
    for harmonic in range(1, max_harmonic + 1, 2):
        signal += np.sin(2.0 * np.pi * harmonic * phase) / harmonic
    return normalize(signal)


def normalize(signal: np.ndarray) -> np.ndarray:
    peak = np.max(np.abs(signal))
    if peak == 0.0:
        return np.zeros(TABLE_SIZE, dtype=np.int16)
    return np.rint(signal * (32767.0 / peak)).astype(np.int16)


def format_level(values: np.ndarray) -> str:
    rows = []
    for start in range(0, TABLE_SIZE, 16):
        row = ", ".join(str(int(value)) for value in values[start : start + 16])
        rows.append(f"    {row},")
    return "    {\n" + "\n".join(rows) + "\n    },\n"


def main() -> None:
    header = [
        "/* Auto-generated by analysis/generate_oscillator_tables.py. */\n",
        "#ifndef OSCILLATOR_TABLES_H\n#define OSCILLATOR_TABLES_H\n\n",
        "#include <stdint.h>\n\n",
        "#define OSCILLATOR_TABLE_SIZE 1024U\n",
        f"#define OSCILLATOR_MIP_LEVEL_COUNT {len(MAX_HARMONICS)}U\n\n",
        "extern const uint16_t oscillator_mip_max_harmonic[OSCILLATOR_MIP_LEVEL_COUNT];\n",
        "extern const int16_t oscillator_saw_mip_tables[OSCILLATOR_MIP_LEVEL_COUNT][OSCILLATOR_TABLE_SIZE];\n",
        "extern const int16_t oscillator_square_mip_tables[OSCILLATOR_MIP_LEVEL_COUNT][OSCILLATOR_TABLE_SIZE];\n\n",
        "#endif /* OSCILLATOR_TABLES_H */\n",
    ]

    source = [
        "/* Auto-generated by analysis/generate_oscillator_tables.py. */\n",
        '#include "oscillator_tables.h"\n\n',
        "const uint16_t oscillator_mip_max_harmonic[OSCILLATOR_MIP_LEVEL_COUNT] = {\n",
        "    " + ", ".join(f"{value}U" for value in MAX_HARMONICS) + "\n};\n\n",
        "const int16_t oscillator_saw_mip_tables[OSCILLATOR_MIP_LEVEL_COUNT][OSCILLATOR_TABLE_SIZE] = {\n",
    ]
    for harmonic_count in MAX_HARMONICS:
        source.append(format_level(generate_saw(harmonic_count)))
    source.append("};\n\n")
    source.append(
        "const int16_t oscillator_square_mip_tables[OSCILLATOR_MIP_LEVEL_COUNT][OSCILLATOR_TABLE_SIZE] = {\n"
    )
    for harmonic_count in MAX_HARMONICS:
        source.append(format_level(generate_square(harmonic_count)))
    source.append("};\n")

    HEADER_PATH.write_text("".join(header), encoding="ascii")
    SOURCE_PATH.write_text("".join(source), encoding="ascii")
    print(f"Generated {HEADER_PATH}")
    print(f"Generated {SOURCE_PATH}")


if __name__ == "__main__":
    main()
